export interface ExplorerTemplate {
  id: string;
  name: string;
  description: string;
  template: string;
  category: string;
  variables: string[];
  icon: string;
}

export const explorerTemplates: ExplorerTemplate[] = [
  // Development
  {
    id: "github-branch",
    name: "GitHub Branch",
    description: "Link to a specific branch in a GitHub repository",
    template: "https://github.com/{org}/{repo}/tree/{branch}",
    category: "Development",
    variables: ["org", "repo", "branch"],
    icon: "branch",
  },
  {
    id: "github-issue",
    name: "GitHub Issue",
    description: "Link directly to a GitHub issue",
    template: "https://github.com/{org}/{repo}/issues/{issue}",
    category: "Development",
    variables: ["org", "repo", "issue"],
    icon: "issue",
  },
  {
    id: "github-pr",
    name: "GitHub Pull Request",
    description: "Link to a pull request for review",
    template: "https://github.com/{org}/{repo}/pull/{pr_number}",
    category: "Development",
    variables: ["org", "repo", "pr_number"],
    icon: "pr",
  },
  {
    id: "github-commit",
    name: "GitHub Commit",
    description: "Link to a specific commit",
    template: "https://github.com/{org}/{repo}/commit/{commit_sha}",
    category: "Development",
    variables: ["org", "repo", "commit_sha"],
    icon: "commit",
  },
  {
    id: "jira-ticket",
    name: "JIRA Ticket",
    description: "Link to a JIRA issue ticket",
    template: "https://{company}.atlassian.net/browse/{ticket_key}",
    category: "Development",
    variables: ["company", "ticket_key"],
    icon: "ticket",
  },
  {
    id: "linear-issue",
    name: "Linear Issue",
    description: "Link to a Linear issue",
    template: "https://linear.app/{workspace}/issue/{issue_id}",
    category: "Development",
    variables: ["workspace", "issue_id"],
    icon: "linear",
  },
  {
    id: "gitlab-mr",
    name: "GitLab Merge Request",
    description: "Link to a GitLab merge request",
    template: "https://gitlab.com/{group}/{project}/-/merge_requests/{mr_number}",
    category: "Development",
    variables: ["group", "project", "mr_number"],
    icon: "gitlab",
  },

  // DevOps & Infrastructure
  {
    id: "grafana-dashboard",
    name: "Grafana Dashboard",
    description: "Link to a Grafana monitoring dashboard",
    template: "https://grafana.com/d/{dashboard_id}?var-env={environment}",
    category: "DevOps",
    variables: ["dashboard_id", "environment"],
    icon: "chart",
  },
  {
    id: "datadog-trace",
    name: "Datadog Trace",
    description: "Link to a specific Datadog trace",
    template: "https://app.datadoghq.com/apm/traces?env={env}&service={service}",
    category: "DevOps",
    variables: ["env", "service"],
    icon: "trace",
  },
  {
    id: "k8s-pod",
    name: "Kubernetes Pod",
    description: "Link to a K8s pod in Google Cloud Console",
    template: "https://console.cloud.google.com/k8s/pod/{region}/{cluster}/{namespace}/{pod_name}",
    category: "DevOps",
    variables: ["region", "cluster", "namespace", "pod_name"],
    icon: "k8s",
  },
  {
    id: "aws-ec2",
    name: "AWS EC2 Instance",
    description: "Link to an EC2 instance in AWS Console",
    template: "https://console.aws.amazon.com/ec2/v2/home?region={region}#Instances:instanceId={instance_id}",
    category: "DevOps",
    variables: ["region", "instance_id"],
    icon: "aws",
  },
  {
    id: "pagerduty-incident",
    name: "PagerDuty Incident",
    description: "Link to a PagerDuty incident",
    template: "https://{subdomain}.pagerduty.com/incidents/{incident_id}",
    category: "DevOps",
    variables: ["subdomain", "incident_id"],
    icon: "pagerduty",
  },
  {
    id: "sentry-error",
    name: "Sentry Error",
    description: "Link to a Sentry error group",
    template: "https://sentry.io/organizations/{org}/issues/{issue_id}",
    category: "DevOps",
    variables: ["org", "issue_id"],
    icon: "sentry",
  },

  // Design
  {
    id: "figma-file",
    name: "Figma File",
    description: "Link to a Figma design file",
    template: "https://figma.com/file/{file_id}",
    category: "Design",
    variables: ["file_id"],
    icon: "figma",
  },
  {
    id: "figma-prototype",
    name: "Figma Prototype",
    description: "Link to a Figma prototype view",
    template: "https://figma.com/proto/{file_id}",
    category: "Design",
    variables: ["file_id"],
    icon: "figma",
  },
  {
    id: "zeroheight",
    name: "Zeroheight Doc",
    description: "Link to a zeroheight design system page",
    template: "https://zeroheight.com/{org}/{page_slug}",
    category: "Design",
    variables: ["org", "page_slug"],
    icon: "doc",
  },
  {
    id: "miro-board",
    name: "Miro Board",
    description: "Link to a Miro brainstorming board",
    template: "https://miro.com/app/board/{board_id}",
    category: "Design",
    variables: ["board_id"],
    icon: "miro",
  },

  // Marketing & Analytics
  {
    id: "utm-link",
    name: "UTM Tracked Link",
    description: "Marketing link with UTM parameters",
    template: "https://{domain}/{path}?utm_source={source}&utm_medium={medium}&utm_campaign={campaign}",
    category: "Marketing",
    variables: ["domain", "path", "source", "medium", "campaign"],
    icon: "campaign",
  },
  {
    id: "bitly-short",
    name: "Short URL",
    description: "Generate a Bitly short link",
    template: "https://bit.ly/{alias}",
    category: "Marketing",
    variables: ["alias"],
    icon: "link",
  },
  {
    id: "ga4-report",
    name: "GA4 Report",
    description: "Link to a Google Analytics 4 report",
    template: "https://analytics.google.com/analytics/web/#/report-web-appexpenence/{report_id}",
    category: "Marketing",
    variables: ["report_id"],
    icon: "analytics",
  },

  // Documentation & Wiki
  {
    id: "notion-page",
    name: "Notion Page",
    description: "Link to a Notion documentation page",
    template: "https://notion.so/{workspace}/{page_id}",
    category: "Docs",
    variables: ["workspace", "page_id"],
    icon: "notion",
  },
  {
    id: "confluence-page",
    name: "Confluence Page",
    description: "Link to an Atlassian Confluence page",
    template: "https://{domain}.atlassian.net/wiki/spaces/{space}/pages/{page_id}",
    category: "Docs",
    variables: ["domain", "space", "page_id"],
    icon: "confluence",
  },
  {
    id: "readme-section",
    name: "README Section",
    description: "Link to a specific section in GitHub README",
    template: "https://github.com/{org}/{repo}#-{section}",
    category: "Docs",
    variables: ["org", "repo", "section"],
    icon: "readme",
  },

  // Communication
  {
    id: "slack-channel",
    name: "Slack Channel",
    description: "Link to a Slack channel",
    template: "https://{workspace}.slack.com/archives/{channel_id}",
    category: "Communication",
    variables: ["workspace", "channel_id"],
    icon: "slack",
  },
  {
    id: "zoom-meeting",
    name: "Zoom Meeting",
    description: "Link to a Zoom meeting room",
    template: "https://zoom.us/j/{meeting_id}?pwd={password}",
    category: "Communication",
    variables: ["meeting_id", "password"],
    icon: "zoom",
  },
  {
    id: "teams-chat",
    name: "Microsoft Teams Chat",
    description: "Link to a Teams conversation",
    template: "https://teams.microsoft.com/l/channel/{channel_id}",
    category: "Communication",
    variables: ["channel_id"],
    icon: "teams",
  },

  // Cloud & Platform
  {
    id: "vercel-deploy",
    name: "Vercel Deployment",
    description: "Link to a Vercel deployment",
    template: "https://vercel.com/{team}/{project}/deployments/{deployment_id}",
    category: "Cloud",
    variables: ["team", "project", "deployment_id"],
    icon: "vercel",
  },
  {
    id: "netlify-site",
    name: "Netlify Site",
    description: "Link to a Netlify hosted site",
    template: "https://{site_name}.netlify.app",
    category: "Cloud",
    variables: ["site_name"],
    icon: "netlify",
  },
  {
    id: "cloudflare-pages",
    name: "Cloudflare Pages",
    description: "Link to a Cloudflare Pages deployment",
    template: "https://{account}.pages.dev/{project}/{branch}",
    category: "Cloud",
    variables: ["account", "project", "branch"],
    icon: "cloudflare",
  },

  // Project Management
  {
    id: "asana-task",
    name: "Asana Task",
    description: "Link to an Asana task",
    template: "https://app.asana.com/0/{project}/{task_id}",
    category: "Project",
    variables: ["project", "task_id"],
    icon: "asana",
  },
  {
    id: "trello-card",
    name: "Trello Card",
    description: "Link to a Trello card",
    template: "https://trello.com/c/{card_id}",
    category: "Project",
    variables: ["card_id"],
    icon: "trello",
  },
  {
    id: "clickup-task",
    name: "ClickUp Task",
    description: "Link to a ClickUp task",
    template: "https://app.clickup.com/t/{task_id}",
    category: "Project",
    variables: ["task_id"],
    icon: "clickup",
  },
];

export const categories = [
  "All",
  "Development",
  "DevOps",
  "Design",
  "Marketing",
  "Docs",
  "Communication",
  "Cloud",
  "Project",
];
